export const testChallengeList = [
    {
        challengeID: "ASDFEOEQ5555",
        challengeTitle: "CPE 1/4 January Weekly Coding Challenge",
        type: "Single",
        format: "Point Based",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.",
        startDate : "2023-5-17" ,
        endDate : "2023-5-20" ,
        numParticipants: 48,
        maxParticipants: 60,
        rating: 2,
        joined: true,
        closed: false,
        bannerImg: "/pingpong.jpg"
} 
,
    {
        challengeID: "ASDFEOEQ5555",
        challengeTitle: "Benny's Februrary E-Marathon",
        type: "Team",
        format: "Time Based",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.",
        startDate : "2023-5-13" ,
        endDate : "2023-5-20" ,
        numParticipants: 20,
        maxParticipants: 30,
        rating: 4,
        joined: true,
        closed: true,
        bannerImg: "/pingpong.jpg"
    },
    {
        challengeID: "ASDFEOEQ5555",
        challengeTitle: "CPE 2/4 January Weekly Coding Challenge",
        type: "Single",
        format: "Point Based",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.",
        startDate : "2023-4-23",
        endDate : "2023-4-27" ,
        numParticipants: 223110,
        maxParticipants: 3003420,
        rating: 3.8,
        joined: true,
        closed: false,
        bannerImg: "/pingpong.jpg"
    },
    {
        challengeID: "ASDFEOEQ5555",
        challengeTitle: "Monthly Table Tennis Championship",
        type: "Duo",
        format: "Double Elimination",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.",
        startDate : "2023-2-12",
        endDate : "2023-2-27" ,
        numParticipants: 3,
        maxParticipants: 16,
        rating: 3.8,
        joined: false,
        closed: true,
        bannerImg: "/pingpong.jpg"
    },
    {
        challengeID: "ASDFEOEQ5555",
        challengeTitle: "Thisfasdfasdfasdfllange Name",
        type: "Sinasdfasdasdfgle",
        format: "Tournamenasasdfasfdt",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.",
        startDate : "2023-3-12",
        endDate : "2023-4-9" ,
        numParticipants: 20,
        maxParticipants: 30,
        rating: 5,
        joined: true,
        closed: false,
        bannerImg: "/pingpong.jpg"
    }
]
