export const testChallengeList = [
    {
        challengeName: 'CPE 1/4 January Weekly Coding Challenge',
        type: 'Single',
        format: 'Point Based',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.',
        date: 'Jan 1 - Jan 7',
        numParticipants: 48,
        maxParticipants: 60,
        rating: 2,
        joined: true,
        closed: false,
        img: '/pingpong.jpg'
    } , 
    {
        challengeName: 'Benny\'s Februrary E-Marathon',
        type: 'Team',
        format: 'Time Based',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.',
        date: 'Jan 3',
        numParticipants: 20,
        maxParticipants: 30,
        rating: 4,
        joined: true,
        closed: true,
        img: '/pingpong.jpg'
    } , 
    {
        challengeName: 'CPE 2/4 January Weekly Coding Challenge',
        type: 'Single',
        format: 'Point Based',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.',
        date: 'Jan 8 - Jan 14',
        numParticipants: 223110,
        maxParticipants: 3003420,
        rating: 3.8,
        joined: true,
        closed: false,
        img: '/pingpong.jpg'
    } , 
    {
        challengeName: 'Monthly Table Tennis Championship',
        type: 'Duo',
        format: 'Double Elimination',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.',
        date: 'Jan 5 - Jan 12',
        numParticipants: 3,
        maxParticipants: 16,
        rating: 3.8,
        joined: false,
        closed: true,
        img: '/pingpong.jpg'
    } , 
    {
        challengeName: 'Thisfasdfasdfasdfllange Name',
        type: 'Sinasdfasdasdfgle',
        format: 'Tournamenasasdfasfdt',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum ultrices justo, nec lobortis est posuere non. Suspendisse potenti. Phasellus.',
        date: '11 Jan - 22 FasdfasdfasdfasdfsaFdasdfeb',
        numParticipants: 20,
        maxParticipants: 30,
        rating: 5,
        joined: true,
        closed: false,
        img: '/pingpong.jpg'
    } , 
]